defaults:
  - data: default
  - model: transformer
  - train: default
  - optimizer: adamw
  - scheduler: none
  - mlflow: local
  - predict: default
  - grpo: default
  - _self_

mode: train
seed: 42

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
